
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.AbstractTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vanshikajoshi
 */
public class Ingredient_Nutrients extends javax.swing.JFrame {
    ArrayList<Ingredients_Nutrient>al;
    mytablemodel tm;
    JLabel lb;
    /**
     * Creates new form Ingredient_Nutrients
     */
    public Ingredient_Nutrients(int id,String name) {
        
        al= new ArrayList<>();
        tm= new mytablemodel();
        lb= new JLabel();
        initComponents();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        int h=(int)d.getHeight();
        int w=(int)d.getWidth();
        lb.setBounds(0, 0, w, h);
        ImageIcon ic =new ImageIcon("src/myuploads/nh12.jpeg");
        Image img=ic.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        ImageIcon im=new ImageIcon(img);
        lb.setIcon(im);
        add(lb);
        setSize(w, h);
        jTable1.setModel(tm);
        setVisible(true);
        
     
        getIngrediantInformation(id, name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void getIngrediantInformation(int id,String name)
    {
    try
        {
         HttpResponse<String> response = Unirest.get("https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/food/ingredients/" + id + "/information?amount=150&unit=grams")
                    .header("X-RapidAPI-Key", "652fb35be6msh43c979dd6e258dap1ede35jsn29e136726656")
                    .header("X-RapidAPI-Host", "spoonacular-recipe-food-nutrition-v1.p.rapidapi.com")
                    .asString();
         if(response.getStatus()==200)
         {
         String ans=response.getBody();
             System.out.println(ans);
             JSONObject mainobj=new JSONObject(ans);
             jLabel2.setText("Name: "+name);
             String Unit=mainobj.get("unit").toString();
             double Amount=(double)mainobj.get("amount");
             String consistancy=mainobj.get("consistency").toString();
             JSONObject obj=mainobj.getJSONObject("nutrition");
             jLabel3.setText("Amount: "+Amount);
             jLabel4.setText("Unit: "+Unit);
             jLabel5.setText("Consistancy: "+consistancy);
             
             JSONArray arr=(JSONArray)obj.getJSONArray("nutrients");
             for(int i=0;i<arr.length();i++)
             {
                 JSONObject subobj=(JSONObject)arr.get(i);
                 String  name1=subobj.get("name").toString();
                 String unit=subobj.get("unit").toString();
                 double amount=(Double)subobj.get("amount");
                 double percent=(Double)subobj.get("percentOfDailyNeeds");
                 
                 al.add(new Ingredients_Nutrient(name1, unit, amount, percent));
                 
             }
             
         }
        }
    catch(Exception ex)
        {
        ex.printStackTrace();
        }
    
    }
    class mytablemodel extends AbstractTableModel
    {

        @Override
        public int getRowCount() {
          return  al.size();
            
        }

        @Override
        public int getColumnCount() {
    return 4;
        }

        @Override
        public Object getValueAt(int i, int j) {
           Ingredients_Nutrient ig=al.get(i);
           if(j==0)
           {
           return ig.name;
           }
           else if(j==1)
           {
           return ig.unit;
           }
           else if(j==2)
           {
           return ig.amount1;
           
           }
           else
           {
           return ig.percentage;
           }
        }

        @Override
        public String getColumnName(int column) {
            String col[]={"Name","Unit","Amount","Percentage"};
            return col[column];
        }
        
    
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Phosphate", 3, 48)); // NOI18N
        jLabel1.setText("               Ingredient Nutrient");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 60, 660, 60);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 140, 160, 30);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(770, 130, 170, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 200, 160, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(770, 200, 180, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 190, 570, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Ingredient_Nutrients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Ingredient_Nutrients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Ingredient_Nutrients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Ingredient_Nutrients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ingredient_Nutrients(0,"").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
