
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import static java.lang.foreign.Arena.global;
import java.net.URI;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.RootPaneUI;
import org.json.JSONArray;
import org.json.JSONObject;
import java.sql.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aparna
 */
public class Search_Recipe extends javax.swing.JFrame {

    /**
     * Creates new form Search_Recipe
     */JLabel lb;
    public Search_Recipe() {
        lb= new JLabel ();
        initComponents();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        int h=(int)d.getHeight();
        int w=(int)d.getWidth();
        lb.setBounds(0, 0, w, h);
        ImageIcon ic =new ImageIcon("src/myuploads/nh6.jpeg");
        Image img=ic.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        ImageIcon im=new ImageIcon(img);
        lb.setIcon(im);
        add(lb);
        setSize(w, h);
    
        setVisible(true);
        
    }
    
    
    
    
    String checkFavorite(int id)
    {
    String ans="";
    try
        {
            ResultSet rs=DBloader.executeSql("select * from favorites where email='"+global.email+"' and recipe_id="+id);
            if(rs.next())
            {
            ans=ans+"added";
            }
            else{
             ans=ans+"notAdded";   
                
            }
            return ans;
        }
    catch(Exception ex)
        {
        ex.printStackTrace();
        return ex.toString();
        }
    }
    
    
    
    String addtoFavorite(int id,String title)
    {
        try
        {
            String ans="";
        ResultSet rs=DBloader.executeSql("select * from favorites where email='"+global.email+"' and recipe_id="+id);
        if(rs.next())
            {
            rs.deleteRow();
            ans=ans+"remove";
            }
        else
            {
                rs.moveToInsertRow();
                rs.updateString("email", global.email);
                rs.updateString("recipe", title);
                rs.updateInt("recipe_id", id);
                rs.insertRow();
                ans=ans+"added";
            }
        return ans;
        }
        catch(Exception ex)
        {
        ex.printStackTrace();
        return ex.toString();
        }
    }
    
    
    
public static BufferedImage scale(BufferedImage src, int w, int h) {
        BufferedImage img
                = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        int x, y;
        int ww = src.getWidth();
        int hh = src.getHeight();
        int[] ys = new int[h];
        for (y = 0; y < h; y++) {
            ys[y] = y * hh / h;
        }
        for (x = 0; x < w; x++) {
            int newX = x * ww / w;
            for (y = 0; y < h; y++) {
                int col = src.getRGB(newX, ys[y]);
                img.setRGB(x, y, col);
            }
        }
        return img;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("Phosphate", 3, 36)); // NOI18N
        lb1.setText("Search Recipe");
        getContentPane().add(lb1);
        lb1.setBounds(480, 20, 280, 50);
        getContentPane().add(tf1);
        tf1.setBounds(180, 120, 220, 30);

        bt1.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        bt1.setText("Search");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(530, 120, 180, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1448, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 1050, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
     
        
       String search=tf1.getText();
       
        search=search.replace(" ", "%20");
        if(search.isEmpty())
        {
            System.out.println("Please type something");
        }
        else
        { 
           try
            {
                
                 HttpResponse<String> res = Unirest.get("https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/recipes/complexSearch?query=" + search)
                        .header("X-RapidAPI-Key", "652fb35be6msh43c979dd6e258dap1ede35jsn29e136726656")
                        .header("X-RapidAPI-Host", "spoonacular-recipe-food-nutrition-v1.p.rapidapi.com")
                        .asString();
                 
                 if(res.getStatus()==200)
                 {
                     
                     String ans=res.getBody();
                     
                     System.out.println(ans);
                     
                     JSONObject mainobj=new JSONObject(ans);
                     
                     JSONArray arr=mainobj.getJSONArray("results");
                    int y=10;
                     for(int i=0;i<arr.length();i++)
                     {
                     JSONObject obj=(JSONObject)arr.get(i);
                      SearchRecipe rec=new SearchRecipe();
                   
                         int id=(int)obj.get("id");
                     
                    
                     String name=obj.get("title").toString();
                     String title=name.replace(" ", "%20");
                     rec.lb1.setText(name);
                     
                     if(obj.has("image"))
                     {
                     String photo=obj.get("image").toString();
                         System.out.println(photo);
                            try
                            {
                             BufferedImage bi = ImageIO.read(new URL(photo));

                            bi = scale(bi, rec.lb2.getWidth(), rec.lb2.getHeight());
                            rec.lb2.setIcon(new ImageIcon(bi));
                            
                            }
                            catch(Exception ex)
                            {
                            ex.printStackTrace();
                            }
                     }
                    rec.bt1.addActionListener(new ActionListener() {
                         @Override
                         public void actionPerformed(ActionEvent e) {
                             ingredients ig=new ingredients(id);
                            
                         }
                    });
                    rec.bt2.addActionListener(new ActionListener() {
                         @Override
                         public void actionPerformed(ActionEvent e) {
                             Details de=new Details(id);
                            
                         }
                    });
                    rec.bt3.addActionListener(new ActionListener() {
                         @Override
                         public void actionPerformed(ActionEvent e) {
                             nutrition nut=new nutrition(id);
                         }
                    });
                    rec.bt5.addActionListener(new ActionListener() {
                         @Override
                         public void actionPerformed(ActionEvent e) {
                             
                             cost_of_recipe cs=new cost_of_recipe(id);
                            
                         }
                    });
                    rec.bt6.addActionListener(new ActionListener() {
                         @Override
                         public void actionPerformed(ActionEvent e) {
                             Taste t1=new Taste(id);
                            
                             
                         }
                    });
                    rec.bt4.addActionListener(new ActionListener() {
                         @Override
                         public void actionPerformed(ActionEvent e) {
                             try
                             {
                               HttpResponse<String> response = Unirest.get("https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/food/videos/search?query=" + title)
                                            .header("X-RapidAPI-Key", "652fb35be6msh43c979dd6e258dap1ede35jsn29e136726656")
                                            .header("X-RapidAPI-Host", "spoonacular-recipe-food-nutrition-v1.p.rapidapi.com")
                                            .asString();
                               if(response.getStatus()==200)
                               {
                               String res=response.getBody();
                                   System.out.println(res);
                                   JSONObject mainobj=new JSONObject(res);
                                   JSONArray arr=mainobj.getJSONArray("videos");
                                   if(!arr.isNull(0))
                                   {
                                   JSONObject obj=(JSONObject)arr.get(0);
                                   String id=obj.get("youTubeId").toString();
                                    URI u=new URI("https://www.youtube.com/results?search_query=" + id);
              
                                    Desktop d=Desktop.getDesktop();
                                       d.browse(u);
                                   }
                                   else
                                   {
                                   URI u=new URI("https://www.youtube.com/watch?v=aDm5WZ3QiIE");
                                   Desktop d=Desktop.getDesktop();
                                   d.browse(u);
                                   }
                                  
                               }
                               
                             }
                             catch(Exception ex)
                             {
                             ex.printStackTrace();;
                             }
                             
                         }
                    });
                    
                   String check= checkFavorite(id);
                   if(check.equals("added"))
                   {
                   rec.bt7.setText("Remove From Favourites");
                   }
                   else
                   {
                   rec.bt7.setText("Add to Favourites");
                   }
//                    
                    rec.bt8.addActionListener(new ActionListener() {
                         @Override
                         public void actionPerformed(ActionEvent e) {
                             Summary sum=new Summary(id);
                            
                         }
                    });
//                    
                    rec.bt7.addActionListener(new ActionListener() {
                         @Override
                         public void actionPerformed(ActionEvent e) {
                             
                           String ans=addtoFavorite( id, name);
                           if(ans.equals("remove"))
                           {
                           rec.bt7.setText("Add to Favourites");
                           }
                           else if(ans.equals("added"))
                           {
                           rec.bt7.setText("Remove from Favourites");
                           }
                           else
                           {
                           JOptionPane.showMessageDialog(rootPane, ans);
                           }
                             
                         }
                    });
//                    
                    
                    
                    
                     rec.setBounds(10, y, 1001, 595);
                     
                     rec.setVisible(true);
                         jPanel1.add(rec);
                         jPanel1.repaint();
                         jPanel1.revalidate();
                         y=y+605;
                     }
                    jPanel1.setPreferredSize(new Dimension(1260, 595*arr.length()));
                     
                 }
            }
           catch(Exception ex)
           {
           ex.printStackTrace();
           }
        }
    }//GEN-LAST:event_bt1ActionPerformed
       
    /**
     * @param args the command line arguments
     */
    
//     public static void main(String args[]) 
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Search_Recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Search_Recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Search_Recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Search_Recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Search_Recipe().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
